

/* PROCEDURE INSERIR DADOS */


--- Procedure para armazenar dados, inserir vários dados de uma só vez.
--- @Declara paramentro ou Variavel
--- Parâmetros de entrada das tabelas CADASTRO_ALUNO - CADASTRO_RESPONSAVEL - ENDERECO_ALUNO - TELEFONE_ALUNO




CREATE PROC INSERIR_DADOS
@NOME_ALUNO VARCHAR(40), @SEXO CHAR(10), @NASCIMENTO DATE, @CPF VARCHAR(14),
@NACIONALIDADE VARCHAR(20), @TURMA_ALUNO VARCHAR(5), @MATRICULA VARCHAR(10),
@OBSERVACAO VARCHAR (300),

@NOME_PAI VARCHAR(40),@CPF_PAI VARCHAR(14),@EMAIL_PAI VARCHAR(50),

@NOME_MAE VARCHAR(40),@CPF_MAE VARCHAR(14),@EMAIL_MAE VARCHAR(50),

@CEP CHAR(10), @RUA VARCHAR(60), @NUMERO VARCHAR(10), @BAIRRO VARCHAR(50), @CIDADE VARCHAR(40), @UF CHAR(2),

@TIPO CHAR(3), @DDD CHAR(3), @NUMERO_TELEFONE VARCHAR(20)

AS
BEGIN
	--- Declarando as chaves estrangeiras
    DECLARE @FK INT

	
	--- Tabela Cadastro Aluno
    INSERT INTO CADASTRO_ALUNO (NOME_ALUNO, SEXO, NASCIMENTO, CPF,
    NACIONALIDADE, TURMA_ALUNO, MATRICULA, OBSERVACAO) 
    VALUES (@NOME_ALUNO,@SEXO,@NASCIMENTO,@CPF,@NACIONALIDADE,@TURMA_ALUNO,@MATRICULA,@OBSERVACAO)
	
    SET @FK = SCOPE_IDENTITY()
	
	--- Tabela Cadastro Responsavel
    INSERT INTO CADASTRO_RESPONSAVEL (NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
    VALUES (@NOME_PAI,@CPF_PAI,@EMAIL_PAI,@NOME_MAE,@CPF_MAE,@EMAIL_MAE,@FK)

	--- Tabela Endereço Aluno
    INSERT INTO ENDERECO_ALUNO (CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
    VALUES(@CEP, @RUA, @NUMERO, @BAIRRO, @CIDADE,@UF, @FK)
		
	--- Tabela Telefone Aluno
    INSERT INTO TELEFONE_ALUNO (TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) 
    VALUES(@TIPO, @DDD, @NUMERO_TELEFONE, @FK)
		        
END;


--- Executar procedure

BEGIN TRANSACTION
EXEC INSERIR_DADOS  'EDUARDA','FEMININO','2024-03-17','57114471512','BRASILEIRO','1F','027','',
                    'IGOR GOMES','26176875936','IGOR@UOL.COM',
                    'CRISTINA NASCIMENTO','36981204492','CRISTINA@UOL.COM',
                    '09140150','RUA OTAVIANO PAZ','N° 482 ','JARDIM SAUDE','SAO PAULO', 'SP',
                    'COM','11','553137049';


--- ROLLBACK PARA CANCELAR 
ROLLBACK TRANSACTION;

--- COMMIT PARA CONFIRMAR
COMMIT TRAN;
					
					
					
--- Apagando Procedure 


DROP PROC INSERIR_DADOS;