

/* PROCEDURE INSERIR DADOS */


--- Procedure para armazenar dados, inserir vários dados de uma só vez.
--- @Declara paramentro ou Variavel
--- Parâmetros de entrada das tabelas CADASTRO_ALUNO - CADASTRO_RESPONSAVEL - ENDERECO_ALUNO - TELEFONE_ALUNO




CREATE PROC INSERIR_DADOS
@NOME_ALUNO VARCHAR(40),@SEXO VARCHAR(12),@NASCIMENTO DATE,@CPF VARCHAR(11),
@NACIONALIDADE VARCHAR(15),@TURMA_ALUNO VARCHAR(5),@MATRICULA VARCHAR(10),
@OBSERVACAO VARCHAR (300),

@NOME_PAI VARCHAR(40),@CPF_PAI VARCHAR(15),@EMAIL_PAI VARCHAR(30),

@NOME_MAE VARCHAR(40),@CPF_MAE VARCHAR(15),@EMAIL_MAE VARCHAR(30),

@RUA VARCHAR(20), @BAIRRO VARCHAR(20), @CIDADE VARCHAR(10), @UF CHAR(2),

@TIPO CHAR(3), @NUMERO VARCHAR(15)

AS
BEGIN
	--- Declarando as chaves estrangeiras
    DECLARE @FK INT
    DECLARE @FKE INT
    DECLARE @FKT INT
	
	--- Tabela Cadastro Aluno
    INSERT INTO CADASTRO_ALUNO VALUES
    (@NOME_ALUNO,@SEXO,@NASCIMENTO,@CPF,@NACIONALIDADE,@TURMA_ALUNO,@MATRICULA,@OBSERVACAO)
	
	
    SET @FK = (SELECT IDALUNO FROM CADASTRO_ALUNO WHERE IDALUNO = @@IDENTITY)
    SET @FKE = (SELECT IDALUNO FROM CADASTRO_ALUNO WHERE IDALUNO = @@IDENTITY)
    SET @FKT = (SELECT IDALUNO FROM CADASTRO_ALUNO WHERE IDALUNO = @@IDENTITY)
	
	--- Tabela Cadastro Responsavel
    INSERT INTO CADASTRO_RESPONSAVEL VALUES
    (@NOME_PAI,@CPF_PAI,@EMAIL_PAI,@NOME_MAE,@CPF_MAE,@EMAIL_MAE,@FK)

	--- Tabela Endereço Aluno
    INSERT INTO ENDERECO_ALUNO VALUES(
        @RUA, @BAIRRO, @CIDADE,@UF, @FKE)
		
	--- Tabela Telefone Aluno
    INSERT INTO TELEFONE_ALUNO VALUES(
        @TIPO, @NUMERO, @FKT)
		        
END;


--- Executar procedure

BEGIN TRANSACTION
EXEC INSERIR_DADOS  'EDUARDA','FEMININO','2024-03-17','57114471512','BRASILEIRO','1F','028','',
                    'IGOR GOMES','26176875936','IGOR@UOL.COM',
                    'CRISTINA NASCIMENTO','36981204492','CRISTINA@UOL.COM',
                    'RUA OTAVIANO PAZ - N:482 ','JARDIM SAUDE','SAO PAULO', 'SP',
                    'COM','9553137049';


COMMIT TRANSACTION;
					
					
					
--- Apagando Procedure 


DROP PROC INSERIR_DADOS;