

--- Criei a terceira tabela para armazenar o endereço do Aluno

/* CREATE TABLE */

--- Estrutura para criar a Tabela Endereço Aluno

CREATE TABLE ENDERECO_ALUNO(
    IDENDERECO INT IDENTITY PRIMARY KEY,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(20) NOT NULL,
    CIDADE VARCHAR(15),
    UF CHAR(2),
    ID_ALUNO INT
);


/* FOREIGN KEY */

--- Comando para inserir Foreign Key (Chave Estrangeira) na tabela Endereço Aluno referente a Tabela Cadastro Aluno

ALTER TABLE ENDERECO_ALUNO ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES CADASTRO_ALUNO(IDALUNO);


/* INSERT INTO VALUES */

--- Comando para adicionar registros na Tabela Endereço Aluno

INSERT INTO ENDERECO_ALUNO VALUES('RUA LABATUT - N: 302','IPIRANGA','SAO PAULO','SP',1);
INSERT INTO ENDERECO_ALUNO VALUES('RUA EUDORA  - N: 99','JABAQUARA','SAO PAULO','SP',2);
INSERT INTO ENDERECO_ALUNO VALUES('RUA MAURO - N: 147','SAUDE','SAO PAULO','SP',3);
INSERT INTO ENDERECO_ALUNO VALUES('RUA CANTAGALO - N: 86','TATUAPE','','SP',4);
INSERT INTO ENDERECO_ALUNO VALUES('RUA DONA JULIA - N: 34','VILA MARIANA','SAO PAULO','SP',5);
INSERT INTO ENDERECO_ALUNO VALUES('RUA GUARANNI - N: 594','TATUAPE','SAO PAULO','SP',6);
INSERT INTO ENDERECO_ALUNO VALUES('RUA BOTELHO - N: 499','JABAQUARA','SAO PAULO','SP',7);
INSERT INTO ENDERECO_ALUNO VALUES('RUA SABARA - N: 380','CENTRO','SAO PAULO','SP',8);
INSERT INTO ENDERECO_ALUNO VALUES('RUA MARANHAO - N: 31','CENTRO','SAO PAULO','',9);
INSERT INTO ENDERECO_ALUNO VALUES('RUA NOVA NIPONIA - N: 505','JABAQUARA','SAO PAULO','SP',10);
INSERT INTO ENDERECO_ALUNO VALUES('RUA AMARAL - N: 72','VILA MARIANA','SAO PAULO','SP',11);
INSERT INTO ENDERECO_ALUNO VALUES('RUA SILVIA - N: 110','CENTRO','SAO PAULO','SP',12);
INSERT INTO ENDERECO_ALUNO VALUES('RUA IBIRAJA - N: 612','JABAQUARA','SAO PAULO','SP',13);
INSERT INTO ENDERECO_ALUNO VALUES('RUA ALAGOAS - N: 48','CENTRO','SAO PAULO','SP',14);
INSERT INTO ENDERECO_ALUNO VALUES('RUA JUARACE - N: 771','VILA MARIANA','SAO PAULO','SP',15);
INSERT INTO ENDERECO_ALUNO VALUES('RUA CAVIANA - N: 82','JABAQUARA','','SP',16);
INSERT INTO ENDERECO_ALUNO VALUES('RUA BATOVI - N: 227','VILA MARIANA','SAO PAULO','SP',17);
INSERT INTO ENDERECO_ALUNO VALUES('RUA ROCHA ALVES - N: 593','ITAQUERA','SAO PAULO','SP',18);
INSERT INTO ENDERECO_ALUNO VALUES('RUA SAO FRANCA LUIS - N: 71','CENTRO','SAO PAULO','SP',19);
INSERT INTO ENDERECO_ALUNO VALUES('RUA JOSE DA SILVA - N: 129','SACOMA','SAO PAULO','SP',20);
INSERT INTO ENDERECO_ALUNO VALUES('RUA VIEIRA ARLINDO - N: 19','SAUDE','','SP',21);
INSERT INTO ENDERECO_ALUNO VALUES('RUA JAPAO - N: 379','CENTRO','SAO PAULO','SP',22);
INSERT INTO ENDERECO_ALUNO VALUES('RUA ANACONDA FRANCA - N: 774','VILA CONCEICAO','SAO PAULO','SP',23);
INSERT INTO ENDERECO_ALUNO VALUES('RUA DOS COQUEIROS - N: 1221','SACOMA','SAO PAULO','SP',24);
INSERT INTO ENDERECO_ALUNO VALUES('RUA ROCHA ALMEIDA - N: 592','SANTA CATARINA','SAO PAULO','SP',25);
INSERT INTO ENDERECO_ALUNO VALUES('RUA SOFIA LURDES - N: 834','SAUDE','SAO PAULO','SP',26);




/* INNER JOIN */

--- Inner Join usando 3 tabelas
--- Buscando Nome e Turma do aluno, Nome Pai, Nome Mãe, Rua e Bairro 


SELECT  A.NOME_ALUNO, A.TURMA_ALUNO,
        R.NOME_PAI, R.NOME_MAE,
        E.RUA, E.BAIRRO
FROM CADASTRO_ALUNO A
INNER JOIN CADASTRO_RESPONSAVEL R
ON A.IDALUNO = R.ID_ALUNO
INNER JOIN ENDERECO_ALUNO E
ON A.IDALUNO = E.ID_ALUNO;


--- Quero todos alunos que moram no (Centro), nome da rua e bairro

SELECT C.IDALUNO, C.NOME_ALUNO,
        E.RUA, E.BAIRRO
FROM CADASTRO_ALUNO C
INNER JOIN ENDERECO_ALUNO E
ON C.IDALUNO = E.ID_ALUNO
WHERE BAIRRO = 'CENTRO';


--- Quero Nome Pai, Nome Mãe, Rua, Bairro, Cidade

SELECT R.IDRESPONSAVEL, R.NOME_PAI, R.NOME_MAE,
        E.RUA, E.BAIRRO, E.CIDADE
FROM CADASTRO_RESPONSAVEL R
INNER JOIN ENDERECO_ALUNO E
ON R.IDRESPONSAVEL = E.IDENDERECO;


--- Quantos alunos moram em cada bairro?
 
SELECT BAIRRO, COUNT(*) AS 'QUANTIDADE'
FROM ENDERECO_ALUNO
GROUP BY BAIRRO;
