
--- Depois de criar a tabela de aluno, criei uma segunda tabela para armazenar as informações dos responsalveis.
--- Criei uma chave estrangeira para relacionar cada responsavel a um aluno.


/* CREATE TABLE */

--- Estrutura para Criar a Tabela Cadastro Responsavel

CREATE TABLE CADASTRO_RESPONSAVEL(
    IDRESPONSAVEL INT IDENTITY(1,1) PRIMARY KEY,
    NOME_PAI VARCHAR(40)NOT NULL,
    CPF_PAI VARCHAR(14) UNIQUE,
    EMAIL_PAI VARCHAR(50)NULL,
    NOME_MAE VARCHAR(40)NOT NULL,
    CPF_MAE VARCHAR(14) UNIQUE, 
    EMAIL_MAE VARCHAR(50)NULL,
    ID_ALUNO INT NOT NULL
);


/* FOREIGN KEY */

--- Comando para inserir Foreign Key (Chave Estrangeira) na tabela Cadastro Responsavel referente a Tabela Cadastro Aluno

ALTER TABLE CADASTRO_RESPONSAVEL ADD CONSTRAINT FK_RESPONSAVEL_ALUNO
FOREIGN KEY (ID_ALUNO) REFERENCES CADASTRO_ALUNO(IDALUNO);


/* INSERT INTO VALUES */

--- Comando para inserir novos registros na Tabela Cadastro Responsalvel

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('ROBSON SILVA',33018891350,'ROBSON@GMAIL.COM','CARLA SILVA',33018891432,'CARLA@GMAIL.COM',1)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('CLAUDIO CAETANO',75893669102,'CLAUDIO@GMAIL.COM','RAQUEL CAETANO',50094799010,'RAQUEL@GMAIL.COM',2)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('MARCELO FERNANDES',57553212312,'MARCELO@GMAIL.COM','RENATA ALVES',3709880767,'RENATA@GMAIL.COM',3)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('WILIAM COSTA',67790089312,'WILIAM@GMAIL.COM','PIETRA SANTOS',44398700345,'PIETRA@GMAIL.COM',4)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('MANOEL JOSE',37799076952,'','AMANDA CAVALCANTE',44376675145,'AMANDA@GMAIL.COM',5)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('MATHIAS HELENO',3411901231,'MATHIAS@GMAIL.COM','HELOISA LIMA',34398700345,'HELOISA@GMAIL.COM',6)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('FRANCISCO ALVES',88500473819,'FRANCISCO@GMAIL.COM','KATIA SANTANA',348493555132,'KATIA@GMAIL.COM',7)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('RONNY LIMA',65577875910,'RONNY@GMAIL.COM','PAMELA RIBEIRO',84795000320,'PAMELA@GMAIL.COM',8)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('FERNANDO GALVAO',33440902990,'FERNANDO@GMAIL.COM','SARA COSTA',33444362990,'SARA@GMAIL.COM',9)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('LEONARDO SANTOS',34387900310,'','KAREN MARTINS',39988004474,'KAREN@GMAIL.COM',10)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO)
VALUES('CAUE NASCIMENTO',4438770102,'CAUE@GMAIL.COM','LUNA CATARINA',47644902231,'LUNA@GMAIL.COM',11)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('JORGE GALDINO',55899033123,'JORGE@GMAIL.COM','NICOLE GALVAO',37000944312,'NICOLE@GMAIL.COM',12)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('ANDRE MAFRA',30098012312,'ANDRE@GMAIL.COM','PALOMA FREITA',30091121676,'PALOMA@GMAIL.COM',13)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('MATEUS LUIZ',7866012344,'MATEUS@GMAIL.COM','LARISSA MEL',336677697445,'LARISSA@GMAIL.COM',14)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO)
VALUES('PATRICK PEREIRA',57700212312,'PATRICK@GMAIL.COM','AURORA FARIAS',53378700345,'AURORA@GMAIL.COM',15)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('JULIANO NETO',32299012312,'JULIANO@GMAIL.COM','SIMONE PEREIRA',33898700345,'SIMONE@GMAIL.COM',16)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('VICTOR ALBERTO',54332331345,'VICTOR@GMAIL.COM','CRISTINA ALVES',33898711345,'CRISTINA@GMAIL.COM',17)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('ROGER JUN',37743900355,'ROGER@GMAIL.COM','BIANCA SILVA',37788700355,'BIANCA@GMAIL.COM',18)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('VAGNER AMARAL',37785516755,'VAGNER@GMAIL.COM','CAMILA CONCEICAO',37788726755,'CAMILA@GMAIL.COM',19)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO)
VALUES('ANTONIO CARLOS',33508700355,'ANTONIO@GMAIL.COM','MARIA MARTINS',33541100355,'MARIA@GMAIL.COM',20)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('CESAR FIGUEIRAS',37760051355,'CESAR@GMAIL.COM','FATIMA SANTOS',37788651355,'FATIMA@GMAIL.COM',21)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('LUCAS BATISTA',37780147755,'LUCAS@GMAIL.COM','BRANCA NAZEN',37788757755,'BRANCA@GMAIL.COM',22)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('ALVARO NEVES',58780147737,'ALVARO@GMAIL.COM','VITORIA NEVES',40988757730,'NVITORIA@GMAIL.COM',23)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO)
VALUES('ISRAEL GUMA',28700147717,'GUMA@GMAIL.COM','IRACI FELIX',20098757748,'IRACI@GMAIL.COM',24)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('ANTONIO CAVALHO',20730147511,'CCANTONIO@GMAIL.COM','RAQUEL MARIA',51789057671,'RAQUELM@GMAIL.COM',25)

INSERT INTO CADASTRO_RESPONSAVEL(NOME_PAI, CPF_PAI, EMAIL_PAI, NOME_MAE, CPF_MAE, EMAIL_MAE, ID_ALUNO) 
VALUES('LUIZ BORJA',31180142985,'BORJAL@GMAIL.COM','BRANCA NAZEN',26488711255,'FERNANDA@GMAIL.COM',26)
;


/* INNER JOIN */

--- Comando Inner Join busca registro de duas ou mais tabelas
--- Comando para concatenar (juntar) dois ou mais registro em um só campo

SELECT  NOME_ALUNO+ ' : '+CPF AS "NOME - CPF",
        NOME_PAI+ ' : ' +CPF_PAI AS "NOME - CPF",
        NOME_MAE+ ' : ' +CPF_MAE AS "NOME - CPF"
FROM CADASTRO_ALUNO
INNER JOIN CADASTRO_RESPONSAVEL
ON IDALUNO = ID_ALUNO;


 SELECT NOME_PAI,
    CONCAT(
        SUBSTRING(CPF_PAI, 1, 3), '.',
        SUBSTRING(CPF_PAI, 4, 3), '.',
        SUBSTRING(CPF_PAI, 7, 3), '-',
        SUBSTRING(CPF_PAI, 10, 2)
    ) AS CPF_FORMATADO
FROM CADASTRO_RESPONSAVEL;


SELECT 	C.NOME_ALUNO,
		R.EMAIL_PAI, R.EMAIL_MAE
FROM CADASTRO_ALUNO C
INNER JOIN CADASTRO_RESPONSAVEL R
ON C.IDALUNO = R.IDRESPONSAVEL;


--- Quero apenas o nome e cpf do pai, Id do aluno (10)

SELECT NOME_PAI, CPF_PAI, ID_ALUNO
FROM CADASTRO_RESPONSAVEL
WHERE IDRESPONSAVEL = 10;


/* SUBCONSULTA */

--- SubConsulta - Busca o Nome Id do Pai dos Alunos da Turma '1A'

SELECT IDRESPONSAVEL, ID_ALUNO, NOME_PAI
FROM CADASTRO_RESPONSAVEL
WHERE ID_ALUNO IN (
    SELECT IDALUNO
    FROM CADASTRO_ALUNO
    WHERE TURMA_ALUNO = '1A'
);


/* DELETE - TRUNCATE */

--- Delete - exclui registros que são indicado na cláusula Where

BEGIN TRANSACTION
DELETE FROM CADASTRO_RESPONSAVEL
WHERE IDRESPONSAVEL IN ('1','7');

--- Cancelar a Transação
ROLLBACK;


--- Delete sem a cláusula Where exclui a tabela inteira(Processo mais lento e com risco)

BEGIN TRANSACTION
DELETE FROM CADASTRO_RESPONSAVEL;

--- Cancelar a Transação
ROLLBACK;


--- Truncate Table - exclui todos os registros da tabela

BEGIN TRANSACTION
TRUNCATE TABLE  CADASTRO_RESPONSAVEL;

--- Cancelar a Transação
ROLLBACK;
