
--- Criei a quarta tabela para armazenar o telefone do aluno 




/* CREATE TABLE */

-- Estrutura para criar Tabela Telefone Aluno

CREATE TABLE TELEFONE_ALUNO(
    IDTELEFONE INT IDENTITY PRIMARY KEY,
    TIPO CHAR(3) CHECK (TIPO IN ('RES','COM','CEL')) NULL,
    NUMERO VARCHAR (15) NULL,
    ID_ALUNO INT
);


/* FOREIGN KEY */

--- Comando para inserir Foreign Key (Chave Estrangeira) na tabela Telefone Aluno referente a Tabela Cadastro Aluno

ALTER TABLE TELEFONE_ALUNO ADD CONSTRAINT FK_TELEFONE_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES CADASTRO_ALUNO(IDALUNO);

/* INSERT INTO VALUES */

--- Comado para inserir registro na Tabela Telefone Aluno

INSERT INTO TELEFONE_ALUNO VALUES('CEL','978929889',1);
INSERT INTO TELEFONE_ALUNO VALUES('RES','24325444',1);
INSERT INTO TELEFONE_ALUNO VALUES('COM','54354354',2);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','999494556',2);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','998574556',3);
INSERT INTO TELEFONE_ALUNO VALUES('RES','45644556',4);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','998387877',5);
INSERT INTO TELEFONE_ALUNO VALUES('RES','32095990',5);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','998771887',6);
INSERT INTO TELEFONE_ALUNO VALUES('COM','35778878',6);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','993474556',7);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','990041598',8);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','998710522',9);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','992225565',10);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','994312589',12);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','997361589',13);
INSERT INTO TELEFONE_ALUNO VALUES('RES','59451589',14);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','994681589',15);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','996671589',17);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','993642289',18);
INSERT INTO TELEFONE_ALUNO VALUES('RES','42447490',18);
INSERT INTO TELEFONE_ALUNO VALUES('RES','29344589',19);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','934988945',21);
INSERT INTO TELEFONE_ALUNO VALUES('RES','59349389',22);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','92949389',24);
INSERT INTO TELEFONE_ALUNO VALUES('RES','23319351',25);
INSERT INTO TELEFONE_ALUNO VALUES('CEL','99019389',26);


/* LEFT JOIN */

--- Comando busca Nome, tipo de telefone e número
--- A função Isnull verifica se uma expressão é nula e a substitui por um valor alternativo, facilitando a leitura de relatórios
--- Left Join retorna todos os registro da tabela da esquerda (Primeira Tabela), e os registros correspondentes da tabela direita
--- é usado para manter discrição da tabela principal mesmo sem dados relacionados


SELECT  A.IDALUNO, A.NOME_ALUNO,
        ISNULL(T.TIPO, 'SEM') AS "TIPO", 
        ISNULL(T.NUMERO,'NUMERO') AS"NUMERO"
FROM CADASTRO_ALUNO A
LEFT JOIN TELEFONE_ALUNO T
ON A.IDALUNO = T.ID_ALUNO;

--- Right Join retorna todos os registros das tabelas da direita, depois do (Right join)
SELECT  A.IDALUNO, A.NOME_ALUNO,
        ISNULL(T.TIPO, 'SEM') AS "TIPO", 
        ISNULL(T.NUMERO,'NUMERO') AS"NUMERO"
FROM CADASTRO_ALUNO A
RIGHT JOIN TELEFONE_ALUNO T
ON A.IDALUNO = T.ID_ALUNO;


--- Quero Nome Aluno, Tipo de Telefone e Número

SELECT	C.NOME_ALUNO,
		T.TIPO, T.NUMERO
FROM CADASTRO_ALUNO C
INNER JOIN TELEFONE_ALUNO T
ON C.IDALUNO = T.ID_ALUNO;


/* OPERADOR LIKE */

--- Comando busca o tipo e número de telefone
--- Like '[52]%' traz os números que começam com o números 5 ou 2

SELECT TIPO, NUMERO
FROM TELEFONE_ALUNO
WHERE NUMERO LIKE '[52]%';


--- Comando busca o Tipo e número de telefone
--- Like '[^52]%' os números que NÃO começam com os números 5 e 2

SELECT TIPO, NUMERO
FROM TELEFONE_ALUNO
WHERE NUMERO LIKE '[^52]%';