

--- Criei a terceira tabela para armazenar o endereço do Aluno

/* CREATE TABLE */

--- Estrutura para criar a Tabela Endereço Aluno

CREATE TABLE ENDERECO_ALUNO(
    IDENDERECO INT IDENTITY PRIMARY KEY,
    CEP CHAR(10) NOT NULL,
    RUA VARCHAR(60) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(40) NULL,
    UF CHAR(2) NULL,
    ID_ALUNO INT NOT NULL
);


/* FOREIGN KEY */

--- Comando para inserir Foreign Key (Chave Estrangeira) na tabela Endereço Aluno referente a Tabela Cadastro Aluno

ALTER TABLE ENDERECO_ALUNO ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES CADASTRO_ALUNO(IDALUNO);


/* INSERT INTO VALUES */

--- Comando para adicionar registros na Tabela Endereço Aluno

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('02022-111','RUA LABATUT','N° 302','IPIRANGA','SAO PAULO','SP',1);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('03033-222','RUA EUDORA','N° 99','JABAQUARA','SAO PAULO','SP',2);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('01001-000','RUA MAURO', 'N° 147','SAUDE','SAO PAULO','SP',3);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('04044-333','RUA CANTAGALO','N° 86','TATUAPE','','SP',4);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('05055-444','RUA DONA JULIA','N° 34','VILA MARIANA','SAO PAULO','SP',5);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('06066-555','RUA GUARANNI','N° 594','TATUAPE','SAO PAULO','SP',6);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('07077-666','RUA BOTELHO','N° 499','JABAQUARA','SAO PAULO','SP',7);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('10010-999','RUA SABARA','N° 380','CENTRO','SAO PAULO','SP',8);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('08088-777','RUA MARANHAO','N° 31','CENTRO','SAO PAULO','',9);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('09099-888','RUA NOVA NIPONIA','N° 505','JABAQUARA','SAO PAULO','SP',10);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('11011-000','RUA AMARAL','N° 72','VILA MARIANA','SAO PAULO','SP',11);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('12012-121','RUA SILVIA','N° 110','CENTRO','SAO PAULO','SP',12);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('13013-232','RUA IBIRAJA','N° 612','JABAQUARA','SAO PAULO','SP',13);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('14014-343','RUA ALAGOAS','N° 48','CENTRO','SAO PAULO','SP',14);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('15015-454','RUA JUARACE','N° 771','VILA MARIANA','SAO PAULO','SP',15);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('16016-565','RUA CAVIANA','N° 82','JABAQUARA','','SP',16);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('17017-676','RUA BATOVI','N° 227','VILA MARIANA','SAO PAULO','SP',17);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('18018-787','RUA ROCHA ALVES','N° 593','ITAQUERA','SAO PAULO','SP',18);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('19019-898','RUA SAO FRANCA LUIS','N° 71','CENTRO','SAO PAULO','SP',19);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('20020-909','RUA JOSE DA SILVA','N° 129','SACOMA','SAO PAULO','SP',20);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('21021-010','RUA VIEIRA ARLINDO','N° 19','SAUDE','','SP',21);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('22022-121','RUA JAPAO','N° 379','CENTRO','SAO PAULO','SP',22);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('23023-232','RUA ANACONDA FRANCA','N° 774','VILA CONCEICAO','SAO PAULO','SP',23);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('24024-343','RUA DOS COQUEIROS','N° 1221','SACOMA','SAO PAULO','SP',24);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('25025-454','RUA ROCHA ALMEIDA','N° 592','SANTA CATARINA','SAO PAULO','SP',25);

INSERT INTO ENDERECO_ALUNO(CEP, RUA, NUMERO, BAIRRO, CIDADE, UF, ID_ALUNO) 
VALUES('26026-565','RUA SOFIA LURDES','N° 834','SAUDE','SAO PAULO','SP',26);




/* INNER JOIN */

--- Inner Join usando 3 tabelas
--- Buscando Nome e Turma do aluno, Nome Pai, Nome Mãe, Cep, Rua, Numero e Bairro 


SELECT  A.NOME_ALUNO, A.TURMA_ALUNO,
        R.NOME_PAI, R.NOME_MAE,
        E.CEP, E.RUA, E.NUMERO, E.BAIRRO
FROM CADASTRO_ALUNO A
INNER JOIN CADASTRO_RESPONSAVEL R
ON A.IDALUNO = R.ID_ALUNO
INNER JOIN ENDERECO_ALUNO E
ON A.IDALUNO = E.ID_ALUNO;


--- Quero cep, rua, numero de todos alunos que moram no (Centro)

SELECT C.IDALUNO, C.NOME_ALUNO,
        E.CEP, E.RUA,E.NUMERO, E.BAIRRO
FROM CADASTRO_ALUNO C
INNER JOIN ENDERECO_ALUNO E
ON C.IDALUNO = E.ID_ALUNO
WHERE BAIRRO = 'CENTRO';


--- Quero Nome Pai, Nome Mãe, Rua, Nuemro, Bairro, Cidade dos responsaveis dos Ids '4','10','11','16','17','20','22','25'

SELECT R.IDRESPONSAVEL, R.NOME_PAI, R.NOME_MAE,
        E.RUA, E.NUMERO, E.BAIRRO, E.CIDADE
FROM CADASTRO_RESPONSAVEL R
INNER JOIN ENDERECO_ALUNO E
ON R.IDRESPONSAVEL = E.IDENDERECO
WHERE IDRESPONSAVEL IN ('4','10','11','16','17','20','22','25');


--- Quantos alunos moram em cada bairro?
 
SELECT BAIRRO, COUNT(*) AS 'QUANTIDADE_DE_ALUNOS'
FROM ENDERECO_ALUNO
GROUP BY BAIRRO;

