
--- Criei a tabela de funcionário (Professores)


/* CREATE TABLE */

--- Estrutura para criar a Tabela Funcionario

CREATE TABLE PROFESSORES(
    IDPROFESSORA INT IDENTITY(1,1) PRIMARY KEY,
    NOME_PROFESSORA VARCHAR(30) NOT NULL,
    TURMA_PROFESSORA VARCHAR(20),
    SALARIO MONEY
);


/* INSERT INTO VALUES */

--- Comando para adicionar registros na Tabela Funcionario

INSERT INTO PROFESSORES VALUES('NEUSA','1A',4500.00);
INSERT INTO PROFESSORES VALUES('CRISTINA','1B',4700.00);
INSERT INTO PROFESSORES VALUES('TANIA','1C',4400.00);
INSERT INTO PROFESSORES VALUES('SONIA','1D',4100.00);
INSERT INTO PROFESSORES VALUES('SUZANA','1E',4100.00);
INSERT INTO PROFESSORES VALUES('KAROL','1F',4100.00);


/* OPERADOR IN */

--- Quero nome e turma das professoras com ID (1) e (3)

SELECT IDPROFESSORA, NOME_PROFESSORA, TURMA_PROFESSORA
FROM PROFESSORES
WHERE IDPROFESSORA IN ('1','3');


/* INNER JOIN */

--- Quero quantidade de alunos e as turmas dos professores de ID (2) e (4)  

SELECT COUNT (*)AS 'QUANTIDADE_ALUNO',
F.IDPROFESSORA, F.NOME_PROFESSORA+ ' --- TURMA --- ' + TURMA_PROFESSORA AS "PROFESSORAS"
FROM CADASTRO_ALUNO A
INNER JOIN PROFESSORES F
ON A.TURMA_ALUNO = F.TURMA_PROFESSORA
WHERE IDPROFESSORA IN ('2','4')
GROUP BY A.TURMA_ALUNO ,F.IDPROFESSORA,F.NOME_PROFESSORA,F.TURMA_PROFESSORA;


--- Quero quantidade de alunos e turmas de todas professoras

SELECT COUNT (*)AS 'QUANTIDADE_ALUNO',
F.NOME_PROFESSORA+ ' --- TURMA -- ' + TURMA_PROFESSORA AS "PROFESSORAS"
FROM CADASTRO_ALUNO A
INNER JOIN PROFESSORES F
ON A.TURMA_ALUNO = F.TURMA_PROFESSORA
GROUP BY A.TURMA_ALUNO ,F.NOME_PROFESSORA,TURMA_PROFESSORA;




--- Quero nome dos alunos, nome das professoras e turmas

SELECT  A.NOME_ALUNO,
F.NOME_PROFESSORA, F.TURMA_PROFESSORA
FROM CADASTRO_ALUNO A
INNER JOIN PROFESSORES F
ON A.TURMA_ALUNO = F.TURMA_PROFESSORA
ORDER BY TURMA_PROFESSORA;


/* CAST - CONVERT */

--- Simulação de aumento de 20% do salário
--- Cast é uma função usada para converter um valor
--- Salario * 1.20. Conta para aumentar 20% do salário
--- AS Decimal(10,2). garante o formato com 2 casas decimais, de moeda. 

SELECT NOME_PROFESSORA, 
       SALARIO,
       CAST(SALARIO * 1.20 AS DECIMAL(10, 2)) AS 'NOVO SALARIO'
FROM PROFESSORES;


--- Simulação de aumento de salário de 30% com a função CONVERT

SELECT NOME_PROFESSORA, 
       SALARIO,
       CONVERT(DECIMAL(10, 2), SALARIO * 1.30) AS 'NOVO SALARIO'
FROM PROFESSORES;


/* UPDATE */

--- Aumento definitivo de 10% do salário do 
BEGIN TRANSACTION
UPDATE PROFESSORES
SET SALARIO = SALARIO * 1.10
WHERE IDPROFESSORA = 3;

COMMIT TRANSACTION;

--- Aumento de 6% do salário
BEGIN TRANSACTION
UPDATE PROFESSORES
SET SALARIO = SALARIO * 1.06
WHERE IDPROFESSORA = 2;

COMMIT TRANSACTION;


/* OPERADOR < - >= - > */

--- Buscar o Funcionário com Salário Menor (<) que 4500

SELECT IDPROFESSORA, NOME_PROFESSORA, SALARIO
FROM PROFESSORES
WHERE SALARIO < 4500;

--- Buscar Funcionário com Salário Menor ou Igual (<=) que 4510

SELECT IDPROFESSORA, NOME_PROFESSORA, SALARIO
FROM PROFESSORES
WHERE SALARIO >= 4510;


--- Buscar o Funcionário com Salário Maior (>) que 4510

SELECT IDPROFESSORA, NOME_PROFESSORA, SALARIO
FROM PROFESSORES
WHERE SALARIO > 4510;


/* FUNÇÃO DE AGREGAÇÃO  MAX - MIN - AVG - SUM */

--- Qual o maior salário?
SELECT MAX(SALARIO) AS 'MAIOR_SALARIO' FROM PROFESSORES;

--- Qual o menor salário?
SELECT MIN(SALARIO) AS 'MENOR_SALARIO' FROM PROFESSORES;

--- Qual a media do total de salário
SELECT AVG(SALARIO) AS 'MEDIA_SALARIO' FROM PROFESSORES;

--- Qual a soma de todos os salários?
SELECT SUM(SALARIO) AS 'SOMA_SALARIOS' FROM PROFESSORES;


/* SUBCONSULTA */

--- SubConsulta - Busca o Nome da Professora dos Alunos da Turma '1B'

SELECT IDPROFESSORA, NOME_PROFESSORA
FROM PROFESSORES
WHERE TURMA_PROFESSORA IN (
    SELECT TURMA_ALUNO
    FROM CADASTRO_ALUNO
    WHERE TURMA_ALUNO = '1F'
);


--- SubConsulta

SELECT * FROM PROFESSORES
WHERE SALARIO <= (SELECT AVG(SALARIO) FROM PROFESSORES); 