--- Criação de um Banco de Dados chamado FICHA DE MATRÍCULAS
--- Com o Objetivo de armazenar e analisar informações de alunos, com dados pessoais, turma e matrícula.


/* CREATE DATABASE */

--- Comando para criar o banco de dados

CREATE DATABASE Ficha_De_Matriculas;


--- Comando para indicar qual banco de dados irei usar

USE Ficha_De_Matriculas;

/* ALTER MODIFY */

--- Aqui vou usar o comando para alterar o nome do banco de dados

ALTER DATABASE Ficha_De_Matriculas
MODIFY NAME =  FICHA_DE_MATRICULAS;


/* CREATE TABLE */

--- Estrutura para criar a tabela cadastro aluno

CREATE TABLE CADASTRO_ALUNO(
    IDALUNO INT IDENTITY(1,1) PRIMARY KEY,
    NOME_ALUNO VARCHAR(40) NOT NULL,
    SEXO VARCHAR(12)NOT NULL CHECK (SEXO IN('MASCULINO','FEMININO')),
    NASCIMENTO DATETIME NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    NACIONALIDADE VARCHAR(15) NOT NULL,
    TURMA_ALUNO VARCHAR(5) NOT NULL,
    MATRICULA VARCHAR(10) UNIQUE,
    OBSERVACAO VARCHAR(300)
);

/* ALTER COLUMN */

--- Comando para Alterar o Tipo de Dado de uma Coluna

ALTER TABLE CADASTRO_ALUNO
ALTER COLUMN NASCIMENTO DATE;


/* INSERT INTO VALUES */

--- Comando para adicionar registros na Tabela Cadastro Aluno

INSERT INTO CADASTRO_ALUNO VALUES('LUCAS','MASCULINO','2023-03-14',54700961130,'BRASILEIRO','1A','001','')
INSERT INTO CADASTRO_ALUNO VALUES('JEAN','MASCULINO','2022-03-29',35703365130,'BRASILEIRO','1B','002','')
INSERT INTO CADASTRO_ALUNO VALUES('RAFAEL','MASCULINO','2021-03-14',32112346590,'BRASILEIRO','1B','003','')
INSERT INTO CADASTRO_ALUNO VALUES('PAULO','MASCULINO','2020-01-22',39933679401,'BRASILEIRO','1C','004','')
INSERT INTO CADASTRO_ALUNO VALUES('CAROL','FEMININO','2023-07-24',45589234279,'BRASILEIRO','1B','005','')
INSERT INTO CADASTRO_ALUNO VALUES('ALINE','FEMININO','2023-09-11',38847800127,'BRASILEIRO','1C','006','')
INSERT INTO CADASTRO_ALUNO VALUES('TATIANA','FEMININO','2021-12-14',33871100990,'BRASILEIRO','1D','007','')
INSERT INTO CADASTRO_ALUNO VALUES('CARLOS','MASCULINO','2020-10-30',45578100123,'BRASILEIRO','1A','008','')
INSERT INTO CADASTRO_ALUNO VALUES('BRUNO','MASCULINO','2023-07-13',27765409890,'BRASILEIRO','1C','009','')
INSERT INTO CADASTRO_ALUNO VALUES('LUKA','MASCULINO','2020-02-19',33018891350,'BRASILEIRO','1C','010','')
INSERT INTO CADASTRO_ALUNO VALUES('DANIELA','FEMININO','2021-06-12',30909855610,'BRASILEIRO','1B','011','')
INSERT INTO CADASTRO_ALUNO VALUES('CAIO','MASCULINO','2023-03-30',31165089730,'BRASILEIRO','1A','012','')
INSERT INTO CADASTRO_ALUNO VALUES('CAMILA','FEMININO','2020-11-07',34412340911,'BRASILEIRO','1A','013','')
INSERT INTO CADASTRO_ALUNO VALUES('KARINA','FEMININO','2021-10-10',30199970248,'BRASILEIRO','1A','014','')
INSERT INTO CADASTRO_ALUNO VALUES('DANILO','MASCULINO','2020-12-31',38800961933,'BRASILEIRO','1B','015','')
INSERT INTO CADASTRO_ALUNO VALUES('SERGIO','MASCULINO','2023-09-19',39700961344,'BRASILEIRO','1C','016','')
INSERT INTO CADASTRO_ALUNO VALUES('AMANDA','FEMININO','2021-02-21',38709000158,'BRASILEIRO','1A','017','')
INSERT INTO CADASTRO_ALUNO VALUES('VICTOR','MASCULINO','2022-07-16',32000273643,'BRASILEIRO','1B','018','')
INSERT INTO CADASTRO_ALUNO VALUES('ROMULO','MASCULINO','2021-08-26',32000274443,'BRASILEIRO','1D','019','')
INSERT INTO CADASTRO_ALUNO VALUES('SANDRO','MASCULINO','2021-01-30',32470274443,'BRASILEIRO','1D','020','')
INSERT INTO CADASTRO_ALUNO VALUES('GESSICA','FEMININO','2022-02-12',32096074443,'BRASILEIRO','1D','021','')
INSERT INTO CADASTRO_ALUNO VALUES('TABATA','FEMININO','2022-03-20',32000241043,'BRASILEIRO','1D','022','')
INSERT INTO CADASTRO_ALUNO VALUES('MAYARA','FEMININO','2021-07-29',39570241671,'BRASILEIRO','1A','023','')
INSERT INTO CADASTRO_ALUNO VALUES('GIOVANNI','MASCULINO','2023-09-17',38810241027,'BRASILEIRO','1A','024','')
INSERT INTO CADASTRO_ALUNO VALUES('ENZO','MASCULINO','2022-02-01',35801241437,'BRASILEIRO','1B','025','')
INSERT INTO CADASTRO_ALUNO VALUES('FRANCIELLE','FEMININO','2023-08-23',39740241311,'BRASILEIRO','1E','026','')
;


--- Comando para ver a estrutura da tabela

SP_HELP CADASTRO_ALUNO;


/* SELECT FROM */

--- Comando para Buscar todos os registros da tabela Cadastro Aluno

SELECT * FROM CADASTRO_ALUNO;


--- Para Simular um comando posso usar CTRL + L

SELECT * FROM CADASTRO_ALUNO;




/* COUNT() - GROUP BY - ORDER BY - DESC - ASC  */

--- Quantos alunos existem no total?

SELECT COUNT(*) AS 'QUANTIDADE DE ALUNOS'
FROM CADASTRO_ALUNO;

--- Quero Nome, Sexo e Turma dos alunos na ordem decrescente. 

SELECT NOME_ALUNO, SEXO, TURMA_ALUNO
FROM CADASTRO_ALUNO
ORDER BY NOME_ALUNO DESC;

--- Quantos alunos do sexo masculino e feminino?

SELECT SEXO, COUNT(*) AS 'TOTAL'
FROM CADASTRO_ALUNO
GROUP BY SEXO;


--- Quais turmas existente?

SELECT TURMA_ALUNO AS 'TURMA EXISTENTE' 
FROM CADASTRO_ALUNO
GROUP BY TURMA_ALUNO;


--- Quantos alunos existem em cada turma? 

SELECT  TURMA_ALUNO, COUNT(*) AS 'TOTAL'
FROM CADASTRO_ALUNO
GROUP BY TURMA_ALUNO;


--- Qual turma tem mais alunos? (Decrescente DESC Z/A)

SELECT TOP 1 TURMA_ALUNO, COUNT(IDALUNO) AS 'QUANTIDADE DE ALUNOS'
FROM CADASTRO_ALUNO
GROUP BY TURMA_ALUNO 
ORDER BY 'QUANTIDADE DE ALUNOS' DESC;


--- Qual turma tem menos alunos?

SELECT TOP 1 TURMA_ALUNO, COUNT(IDALUNO) AS "TOTAL MENOR"
FROM CADASTRO_ALUNO
GROUP BY TURMA_ALUNO
ORDER BY [TOTAL MENOR] ASC;


--- Quero nome e Id dos alunos na ordem (Crescente ASC POR NOME - A/Z)

SELECT NOME_ALUNO,IDALUNO 
FROM CADASTRO_ALUNO
ORDER BY NOME_ALUNO ASC;


--- Quero a data de nascimento na oredem crescente

SELECT NASCIMENTO 
FROM CADASTRO_ALUNO
ORDER BY NASCIMENTO ASC;



/*Operados = <> - < - > LIKE AND - OR - IN - BETWEEN */

--- Nome dos alunos da turma 1A

SELECT NOME_ALUNO 
FROM CADASTRO_ALUNO
WHERE TURMA_ALUNO = '1A';


--- Quais os Alunos da turma 1B?

SELECT NOME_ALUNO, TURMA_ALUNO
FROM CADASTRO_ALUNO
WHERE TURMA_ALUNO = '1B';


--- Quais alunos nascidos após 2023?

SELECT NOME_ALUNO, NASCIMENTO
FROM CADASTRO_ALUNO
WHERE NASCIMENTO > '2023';


--- Quais alunos começam com a letra C?

SELECT IDALUNO, NOME_ALUNO 
FROM CADASTRO_ALUNO
WHERE NOME_ALUNO LIKE 'C%';


--- Quais alunos que terminam com a Letra 'A'

SELECT IDALUNO, NOME_ALUNO 
FROM CADASTRO_ALUNO
WHERE NOME_ALUNO LIKE '%A';


--- Buscar os alunos do sexo masculino da turma '1A' - Operador  AND

SELECT NOME_ALUNO, SEXO, TURMA_ALUNO
FROM CADASTRO_ALUNO
WHERE SEXO = 'MASCULINO' AND TURMA_ALUNO = '1A';

--- Bucar os alunos do sexo masculino ou feminino da turma '1B' - Operadores  OR e AND

SELECT NOME_ALUNO , SEXO, TURMA_ALUNO
FROM CADASTRO_ALUNO
WHERE (SEXO = 'Masculino' OR SEXO = 'Feminino') AND  TURMA_ALUNO = '1B';


--- Buscar os alunos onde o sexo seja diferente de Masculino - Operador <>

SELECT NOME_ALUNO, SEXO, TURMA_ALUNO
FROM CADASTRO_ALUNO
WHERE SEXO <> 'Masculino';

--- Buscar os alunos onde o sexo seja diferente de feminino - Operador <>

SELECT NOME_ALUNO, SEXO, TURMA_ALUNO
FROM CADASTRO_ALUNO
WHERE SEXO <> 'F';


--- Quantidade de alunos masculino e feminino - Operador (IN)

SELECT SEXO, COUNT(*) AS 'TOTAL ALUNOS'
FROM CADASTRO_ALUNO
WHERE SEXO IN ('Masculino','Feminino')
GROUP BY SEXO;

--- Busca as matriculas 002, 008 e 016 - Operador (IN)

SELECT NOME_ALUNO, SEXO, MATRICULA
FROM CADASTRO_ALUNO
WHERE MATRICULA IN (002,016,008);



--- Between buscar os alunos que nasceram entre 01-01-2022 até 30-06-2023

SELECT NOME_ALUNO , NASCIMENTO
FROM CADASTRO_ALUNO
WHERE NASCIMENTO BETWEEN '2022-01-01' AND '2023-06-30'
ORDER BY NASCIMENTO;





/* DATEDIFF - GETDATE */

--- Calcular idade dos alunos:

SELECT NOME_ALUNO,
	DATEDIFF(YEAR, NASCIMENTO, GETDATE()) AS "IDADE"
FROM CADASTRO_ALUNO;


--- Quais alunos são mais velhos?

SELECT  NOME_ALUNO, DATEDIFF(YEAR, NASCIMENTO, GETDATE()) AS IDADE
FROM CADASTRO_ALUNO
WHERE DATEDIFF(YEAR, NASCIMENTO, GETDATE()) = 6;


--- Quero saber quantos dias tem do nascimento até a data atual

SELECT 
    NOME_ALUNO, 
    NASCIMENTO, 
    DATEDIFF(DAY, NASCIMENTO, GETDATE()) AS 'DIAS'
FROM CADASTRO_ALUNO
WHERE DATEDIFF(DAY, NASCIMENTO, GETDATE()) <= 10000;



/* TOP PERCENT */

--- Quais são os primeiros 5 alunos cadastrados?

SELECT TOP 5 IDALUNO, NOME_ALUNO 
FROM CADASTRO_ALUNO;


--- Quero 10% do total de registro da tabela de cadastro alunos 

--- Quero 10% do total de registro da tabela de cadastro alunos 

SELECT TOP 10 PERCENT IDALUNO, NOME_ALUNO, TURMA_ALUNO, SEXO
FROM CADASTRO_ALUNO;



/* HAVING - UPDATE */

--- Buscar as turmas com mais de 5 alunos?

SELECT TURMA_ALUNO, COUNT(*) AS 'TOTAL ALUNOS'
FROM CADASTRO_ALUNO
GROUP BY TURMA_ALUNO
HAVING COUNT(*) > 6;

--- Atualize o registro do campo (Nacionalidade) do Idaluno '1' para Italiano

UPDATE CADASTRO_ALUNO
SET NACIONALIDADE = 'ITALIANO'
WHERE IDALUNO = 1;


--- Atualize o registro no campo (Observação) do Idaluno '1' 

UPDATE CADASTRO_ALUNO
SET OBSERVACAO = 'LUCAS ESTA SE ALIMENTO BEM'
WHERE IDALUNO = 5;




/* DELETE - TRUNCATE */

--- Delete exclui registros que são indicado na cláusula Where

DELETE FROM CADASTRO_ALUNO
WHERE IDALUNO IN ('1','7');

--- Delete sem a cláusula Where exclui a tabela inteira(Processo mais lento e com risco)

DELETE FROM CADASTRO_ALUNO;

--- Truncate Table - exclui todos os registros da tabela

TRUNCATE TABLE  CADASTRO_ALUNO;



/* CALCULAR DIAS DA SEMANA */


--- Data e Horas do Dia Atual
SELECT GETDATE();

---- Data do Dia Anterior e Horas do Dia Atual
SELECT DATEADD(D,-1,GETDATE()) AS 'ONTEM';

--- Data do dia anterior
SELECT CAST(DATEADD(D,-1,GETDATE())AS DATE) AS 'DATA_DE_ONTEM';

--- Data do Dia Atual
SELECT CAST(GETDATE()AS DATE)AS 'DATA_DE_HOJE';

--- Quantidade de Semana do Início do Ano até Hoje
SELECT DATEPART(WEEK,GETDATE()) AS 'QUANTIDADE_DE_SEMANAS';

--- Quantidade de Semana do Início do Ano até Mês Passado
SELECT DATEPART(WEEK,GETDATE()) - 1 AS 'QUANTIDADE_DE_SEMANAS';