
--- Criei a quarta tabela para armazenar o telefone do aluno 




/* CREATE TABLE */

-- Estrutura para criar Tabela Telefone Aluno

CREATE TABLE TELEFONE_ALUNO(
    IDTELEFONE INT IDENTITY(1,1) PRIMARY KEY,
    TIPO CHAR(3) NOT NULL CHECK (TIPO IN ('RES','COM','CEL')),
    DDD CHAR(3) NOT NULL,
    NUMERO_TELEFONE VARCHAR (20) NOT NULL,
    ID_ALUNO INT
);


/* FOREIGN KEY */

--- Comando para inserir Foreign Key (Chave Estrangeira) na tabela Telefone Aluno referente a Tabela Cadastro Aluno

ALTER TABLE TELEFONE_ALUNO ADD CONSTRAINT FK_TELEFONE_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES CADASTRO_ALUNO(IDALUNO);

/* INSERT INTO VALUES */

--- Comado para inserir registro na Tabela Telefone Aluno

INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','978929889',1);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('COM','11','54354354',2);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','998574556',3);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('RES','11','45644556',4);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('RES','11','32095990',5);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','998771887',6);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','993474556',7);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','990041598',8);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','998710522',9);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','992225565',10);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('RES','11','24325444',11);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','994312589',12);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','997361589',13);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('RES','11','59451589',14);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','994681589',15);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','999494556',16);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','996671589',17);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','993642289',18);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('RES','11','29344589',19);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('RES','11','42447490',20);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','934988945',21);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('RES','11','59349389',22);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','998387877',23);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','92949389',24);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('RES','11','23319351',25);
INSERT INTO TELEFONE_ALUNO(TIPO, DDD, NUMERO_TELEFONE, ID_ALUNO) VALUES('CEL','11','99019389',26);





-- Todos os telefones cadastrados

SELECT * FROM TELEFONE_ALUNO;

-- Telefones de um aluno específico

SELECT * FROM TELEFONE_ALUNO
WHERE ID_ALUNO = 10;

-- Buscar por tipo

SELECT * FROM TELEFONE_ALUNO
WHERE TIPO = 'CEL';


-- Alunos com mais de um telefone cadastrado

SELECT ID_ALUNO, COUNT(*) AS TOTAL_TELEFONES
FROM TELEFONE_ALUNO
GROUP BY ID_ALUNO
HAVING COUNT(*) > 1;

-- Telefones de um DDD específico

SELECT * FROM TELEFONE_ALUNO
WHERE DDD = '12';



-- Quantidade de telefones por tipo

SELECT TIPO, COUNT(*) AS TOTAL
FROM TELEFONE_ALUNO
GROUP BY TIPO;

-- Quantidade de telefones por DDD

SELECT DDD, COUNT(*) AS TOTAL
FROM TELEFONE_ALUNO
GROUP BY DDD
ORDER BY TOTAL DESC;


-- Número formatado com DDD

SELECT ID_ALUNO, TIPO,
    '(' + DDD + ') ' + NUMERO_TELEFONE AS TELEFONE_FORMATADO
FROM TELEFONE_ALUNO;



-- Nome do aluno + todos os seus telefones

SELECT A.NOME_ALUNO, T.TIPO, T.DDD, T.NUMERO_TELEFONE
FROM CADASTRO_ALUNO A
INNER JOIN TELEFONE_ALUNO T 
ON A.IDALUNO = T.ID_ALUNO;

-- Alunos com telefone celular cadastrado

SELECT A.NOME_ALUNO, T.NUMERO_TELEFONE
FROM CADASTRO_ALUNO A
INNER JOIN TELEFONE_ALUNO T ON A.IDALUNO = T.ID_ALUNO
WHERE T.TIPO = 'CEL';

-- Alunos com telefone RES cadastrado

SELECT A.NOME_ALUNO, T.NUMERO_TELEFONE
FROM CADASTRO_ALUNO A
INNER JOIN TELEFONE_ALUNO T ON A.IDALUNO = T.ID_ALUNO
WHERE T.TIPO = 'RES';




/* OPERADOR LIKE */

--- Comando busca o tipo e número de telefone
--- Like '[52]%' traz os números que começam com o números 5 ou 2

SELECT TIPO, NUMERO_TELEFONE
FROM TELEFONE_ALUNO
WHERE NUMERO_TELEFONE LIKE '[52]%';


--- Comando busca o Tipo e número de telefone
--- Like '[^52]%' os números que NÃO começam com os números 5 e 2

SELECT TIPO, NUMERO_TELEFONE
FROM TELEFONE_ALUNO
WHERE NUMERO_TELEFONE LIKE '[^52]%';