

--- Criei uma Trigger(Gatilho) - Ela dispara no UPDATE 
--- Verifica se a  Turma mundou
--- Compara valor Antigo X Novo
--- Salva um Log na Tabela Histórico




--- Tabela Cadastro Aluno 

CREATE TABLE CADASTRO_ALUNO(
    IDALUNO INT IDENTITY(1,1) PRIMARY KEY,
    NOME_ALUNO VARCHAR(40) NOT NULL,
    SEXO VARCHAR(12)NOT NULL CHECK (SEXO IN('MASCULINO','FEMININO')),
    NASCIMENTO DATETIME NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    NACIONALIDADE VARCHAR(15) NOT NULL,
    TURMA_ALUNO VARCHAR(5) NOT NULL,
    MATRICULA VARCHAR(10) UNIQUE,
    OBSERVACAO VARCHAR(300)
);


--- Tabela Histórico 

CREATE TABLE HISTORICO_TURMA (
    IDHISTORICO INT IDENTITY PRIMARY KEY,
    NOME_ALUNO VARCHAR(40) NOT NULL,
    SEXO VARCHAR(12)NOT NULL CHECK (SEXO IN('MASCULINO','FEMININO')),
    NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    NACIONALIDADE VARCHAR(15) NOT NULL,
    TURMA_ALUNO_ANTIGA VARCHAR(5) NOT NULL,
    TURMA_ALUNO_NOVA VARCHAR(5) NOT NULL,
    MATRICULA_ALUNO VARCHAR(10) UNIQUE,
    DATA DATETIME,
    USUARIO VARCHAR(20)
);



--- Trigger TRG_Histórico_Turma 

CREATE TRIGGER TRG_HISTORICO_TURMA
ON dbo.CADASTRO_ALUNO --- Vai ser na Tabela Cadastro Aluno
FOR UPDATE AS --- Só despara quando for UPDATE
IF UPDATE (TURMA_ALUNO)
BEGIN
			--- Declarando a Variavel da Tabela Histórico
            DECLARE @IDALUNO INT
            DECLARE @NOME_ALUNO VARCHAR(40)
            DECLARE @SEXO VARCHAR(12)
            DECLARE @NASCIMENTO DATE
            DECLARE @CPF VARCHAR(11)
            DECLARE @NACIONALIDADE VARCHAR(15)
            DECLARE @TURMA_ALUNO VARCHAR (5)
            DECLARE @TURMA_ALUNO_NOVA VARCHAR (5)
            DECLARE @MATRICULA VARCHAR (10)
            DECLARE @DATA DATETIME
            DECLARE @USUARIO VARCHAR(20)
            --- Inserted vai Mnater os mesmo registros
			--- Deleted vai Apagar o Registro 'Antigo'
            SELECT @IDALUNO = IDALUNO FROM inserted
            SELECT @NOME_ALUNO = NOME_ALUNO FROM inserted
            SELECT @SEXO = SEXO FROM inserted
            SELECT @NASCIMENTO = NASCIMENTO FROM inserted
            SELECT @CPF = CPF FROM inserted
            SELECT @NACIONALIDADE = NACIONALIDADE FROM inserted
            SELECT @TURMA_ALUNO = TURMA_ALUNO FROM deleted
            SELECT @TURMA_ALUNO_NOVA = TURMA_ALUNO FROM inserted
            SELECT @MATRICULA = MATRICULA FROM inserted

            --- Set - para Mostrar a Data Atual e o Usuário que esta fazendo o UPDATE 
            SET @DATA = GETDATE() 
            SET @USUARIO = SUSER_NAME()

			--- Insirindo na Tabela Histórico
            INSERT INTO HISTORICO_TURMA VALUES (@NOME_ALUNO,@SEXO,@NASCIMENTO,@CPF,@NACIONALIDADE,
            @TURMA_ALUNO,@TURMA_ALUNO_NOVA,@MATRICULA,@DATA,@USUARIO)

			--- Imprimir a Mensagem 
			
            PRINT 'TRIGGER EXECUTDA COM SUCESSO'
END;


--- Update Turma Aluno - Idaluno '23'

UPDATE CADASTRO_ALUNO
SET TURMA_ALUNO = '1B'
WHERE IDALUNO = 23;

--- Selects para conferir o antes e depois.

SELECT * FROM CADASTRO_ALUNO;

SELECT * FROM HISTORICO_TURMA;






--- Histórico Pagamento 

CREATE TABLE  HISTORICO_PAGAMENTO(
    IDHISTORICOSAL INT PRIMARY KEY IDENTITY,
    NOME_PROFESSORA VARCHAR (30),
    TURMA_PROFESSORES VARCHAR (20),
    SALARIO_ANTIGO MONEY NOT NULL,
    SALARIO_NOVO MONEY NOT NULL,
    DATA DATETIME,
    USUARIO VARCHAR(20)
);


--- Trigger Histórico Salario

CREATE TRIGGER TRG_HISTORICO_SALARIO
ON dbo.PROFESSORES
FOR UPDATE AS
IF UPDATE (SALARIO)
BEGIN
        DECLARE @IDPROFESSORA INT
        DECLARE @NOME_PROFESSORA VARCHAR (30)
        DECLARE @TURMA_PROFESSORA VARCHAR (20)
        DECLARE @SALARIO MONEY
        DECLARE @SALARIO_NOVO MONEY
        DECLARE @DATA DATETIME
        DECLARE @USUARIO VARCHAR(20)
        
        SELECT @IDPROFESSORA = IDPROFESSORA FROM inserted
        SELECT @NOME_PROFESSORA = NOME_PROFESSORA  FROM inserted
        SELECT @TURMA_PROFESSORA = TURMA_PROFESSORA FROM inserted
        SELECT @SALARIO = SALARIO FROM DELETED
        SELECT @SALARIO_NOVO = SALARIO FROM inserted
    
        SET @DATA = GETDATE()
        SET @USUARIO = SUSER_NAME()
        
        INSERT INTO HISTORICO_PAGAMENTO VALUES(@NOME_PROFESSORA ,@TURMA_PROFESSORA,
                    @SALARIO,@SALARIO_NOVO,@DATA ,@USUARIO)
                    
            PRINT 'TRIGGER EXECUTADA COM SUCESSO'


END;







--- Aumento de 10% do Salario 

UPDATE PROFESSORES
SET SALARIO = SALARIO * 1.10 
WHERE IDPROFESSORA = 1;

--- Aumento de 6% do Salario

UPDATE PROFESSORES
SET SALARIO = SALARIO * 1.06
WHERE IDPROFESSORA = 2;

--- Selects para conferir o antes e depois.

SELECT * FROM PROFESSORES;

SELECT * FROM HISTORICO_PAGAMENTO;